increase timeout for hasauth.test.js
because it times out with 40000ms on Travis with Node 10. See https://travis-ci.org/PieterGit/cgm-remote-monitor/jobs/401307860

not ok 192 pluginbase does stuff
  AssertionError: expected -1 to be above -1
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at containsLine (tests/hashauth.test.js:163:41)
      at Window.mockConfirm [as alert] (tests/hashauth.test.js:165:7)
      at Object.u.addBasals (tmp/js/bundle.js:9:2577816)
      at Object.o.scroll (tmp/js/bundle.js:9:2485436)
      at V (tmp/js/bundle.js:9:3092518)
      at Timeout.e [as _onTimeout] (tmp/js/bundle.js:9:3106675)
# tests 192
# pass 191
# fail 1