fix azure problems
if use latest nodejs on Azure

if it want yargs, we'll give it

> Nightscout@0.10.3-dev-20180723 postinstall D:\home\site\wwwroot
> webpack --mode production --config webpack.config.js && npm run-script update-buster

module.js:549
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\webpack\bin\webpack.js:16:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3